# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM node:22-alpine
RUN npm install -g npm@latest

COPY . /app
WORKDIR ${FOLDER}

ENV NODE_ENV=development

USER 1000:1000

EXPOSE 4321
ENV PORT=4321
ENV HOST="0.0.0.0"

CMD ["npm", "run", "dev"]
